In [1]:
!pip install --upgrade tensorflow==1.5.0
!pip install --upgrade keras==2.1.4

    100% |████████████████████████████████| 44.4MB 737kB/s 
    100% |████████████████████████████████| 3.0MB 10.2MB/s 
    100% |████████████████████████████████| 890kB 11.5MB/s 
  Running setup.py bdist_wheel for html5lib ... - \ done
  Stored in directory: /root/.cache/pip/wheels/50/ae/f9/d2b189788efcf61d1ee0e36045476735c838898eef1cad6e29
Successfully built html5lib
  Found existing installation: bleach 3.0.2
    Uninstalling bleach-3.0.2:
      Successfully uninstalled bleach-3.0.2
  Found existing installation: tensorflow 1.12.0rc1
    Uninstalling tensorflow-1.12.0rc1:
      Successfully uninstalled tensorflow-1.12.0rc1
    100% |████████████████████████████████| 327kB 7.0MB/s 
  Found existing installation: Keras 2.1.6
    Uninstalling Keras-2.1.6:
      Successfully uninstalled Keras-2.1.6


test-tf.py

In [2]:
import tensorflow as tf
sess = tf.Session()
hello = tf.constant("Hello")
print(sess.run(hello))

b'Hello'


test_add.py

In [3]:
import tensorflow as tf

#定数を定義
a = tf.constant(100)
b = tf.constant(30)

#演算を定義
add_op = a + b

#セッションを開始する
sess = tf.Session()
res = sess.run(add_op)
print(res)

130


test_mul.py

In [7]:
import tensorflow as tf

a = tf.constant(10)
b = tf.constant(20)
c = tf.constant(30)

mul_op = (a + b) * c

sess = tf.Session()
res = sess.run(mul_op)
print(res)

900


test_mul_tb.py

In [8]:
import tensorflow as tf

a = tf.constant(10, name="10")
b = tf.constant(20, name="20")
c = tf.constant(30, name="30")

add_op = tf.add(a, b, name="add")
mul_op = tf.multiply(add_op, c, name="mul")

sess = tf.Session()
res = sess.run(mul_op)
print(res)

tf.summary.FileWriter("./logs", sess.graph)

900


test_var_tb.py

In [9]:
import tensorflow as tf

v = tf.Variable(0, name="v")

a = tf.constant(10, name="10")
b = tf.constant(20, name="20")
c = tf.constant(30, name="30")

mul_op = tf.multiply(a, b, name="mul")
assign_op = tf.assign(v, mul_op)

sess = tf.Session()

sess.run(assign_op)

tf.summary.FileWriter("./logs", sess.graph)

res = sess.run(v)
print(res)

200


test_placeholder.py

In [11]:
import tensorflow as tf

#ブレースホルダを定義
a = tf.placeholder(tf.int32, [5])

#ベクトルを2倍にする演算を定義
two = tf.constant(2)
x2_op = a * two


sess = tf.Session()

res1 = sess.run(x2_op, feed_dict={a:[1, 2, 3, 4, 5]})
print(res1)
res2 = sess.run(x2_op, feed_dict={a:[5, 6, 7, 10, 100]})
print(res2)

[ 2  4  6  8 10]
[ 10  12  14  20 200]


test_placeholder2.py

In [13]:
import tensorflow as tf

a = tf.placeholder(tf.int32, [None, 2])

two = tf.constant(2)
x2_op = a * two


sess = tf.Session()

sample_list = [[1, 1], [2, 2], [3, 3], [4, 4]]
res = sess.run(x2_op, feed_dict={a:sample_list})
print(res)

[[2 2]
 [4 4]
 [6 6]
 [8 8]]
