Numpyの使い方を復習してみる

In [0]:
import numpy as np

Numpy配列の初期化

In [2]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
print(np.zeros(10))
print(np.zeros((3, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
print(np.arange(5))
print(np.arange(2, 9))
print(np.arange(5, 8, 0.5))

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


行列計算

In [11]:
a = np.arange(1, 6)
b = a * 2
print(a)
print(b)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [12]:
x = np.arange(10)
y = x * 3 + 5
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


Numpy配列の次元数を数える

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

b = np.array([[1, 2], [3, 4], [5, 6]])
print(b.shape)

(2, 3)
(3, 2)


Numpy配列で次元数を変換する

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print("a = {}".format(a))
b = a.flatten()
print("b = {}".format(b))

a = [[1 2 3]
 [4 5 6]]
b = [1 2 3 4 5 6]


In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


Numpy配列の要素にアクセスする方法

In [18]:
v = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a = v[0]
b = v[1:]
c = v[: , 0]
print("a = ", a)
print("b = ", b)
print("c = ", c)

a =  [1 2 3]
b =  [[4 5 6]
 [7 8 9]]
c =  [1 4 7]
